# Generated by Django 2.2.4 on 2019-11-11 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('product_no', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.IntegerField()),
                ('product_qty', models.IntegerField()),
                ('merchant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.MerchantMdel')),
            ],
        ),
    ]
